name: open_peeps
description: A user-avatar package based on the open peeps illustration library. 
version: 1.0.0
homepage: https://github.com/JensHor/open_peeps/tree/main/packages/open_peeps
repository: https://github.com/JensHor/open_peeps/tree/main/packages/open_peeps
issue_tracker: https://github.com/JensHor/open_peeps/issues
documentation: https://github.com/JensHor/open_peeps

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  open_peeps_models: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0

flutter:
  assets:
    - assets/atoms/accessories/
    - assets/atoms/body/
    - assets/atoms/face/
    - assets/atoms/facial-hair/
    - assets/atoms/head/
    - assets/atoms/pose/