name: open_peeps_models
description: Contains models for the open_peeps package.
version: 1.0.0
homepage: https://github.com/JensHor/open_peeps/tree/main/packages/open_peeps_models
repository: https://github.com/JensHor/open_peeps/tree/main/packages/open_peeps_models
issue_tracker: https://github.com/JensHor/open_peeps/issues
documentation: https://github.com/JensHor/open_peeps

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  test: ^1.16.0
  very_good_analysis: ^3.0.0
dependencies: {freezed_annotation: ^2.0.3}
